
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: Bf1im16y
      POSTGRES_DB: openwhatsapp
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://alex:Bf1im16y@db:5432/openwhatsapp
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

volumes:
  db_data: